[project]
name = "my-flask-app"
version = "0.1.0"
description = "A Flask web application"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "pytest>=8.4.2",
    "pytest-html>=4.1.1",
    "requests>=2.32.5",
]
